# Generated by Django 3.2.14 on 2022-07-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Email',
            field=models.EmailField(default='username@example.com', max_length=254),
        ),
    ]
