# Generated by Django 3.2.14 on 2022-07-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220721_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Subject',
            field=models.CharField(default='No Subject', max_length=255, null=True),
        ),
    ]
