# Generated by Django 3.2.13 on 2022-07-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220713_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='blog/'),
        ),
    ]
